---
# Environment Secrets Template
# Template file for environment-specific secrets and API keys

# Development Environment
development:
  # LLM Provider API Keys
  openai:
    api_key: "${OPENAI_API_KEY:}"
    organization_id: "${OPENAI_ORG_ID:}"
    
  anthropic:
    api_key: "${ANTHROPIC_API_KEY:}"
    
  google:
    cloud_project_id: "${GOOGLE_CLOUD_PROJECT_ID:}"
    service_account_key: "${GOOGLE_SERVICE_ACCOUNT_KEY:}"
    vertex_ai_location: "${VERTEX_AI_LOCATION:us-central1}"
    
  azure:
    openai_api_key: "${AZURE_OPENAI_API_KEY:}"
    openai_endpoint: "${AZURE_OPENAI_ENDPOINT:}"
    openai_api_version: "${AZURE_OPENAI_API_VERSION:2023-12-01-preview}"
  
  # Database secrets
  database:
    connection_string: "${DATABASE_URL:}"
    encryption_key: "${DB_ENCRYPTION_KEY:}"
    
  # Storage secrets
  storage:
    bigquery_key: "${BIGQUERY_SERVICE_ACCOUNT_KEY:}"
    s3_access_key: "${AWS_ACCESS_KEY_ID:}"
    s3_secret_key: "${AWS_SECRET_ACCESS_KEY:}"
    
  # External integrations
  integrations:
    stripe_secret_key: "${STRIPE_SECRET_KEY:}"
    webhook_secret: "${WEBHOOK_SECRET:}"
    jwt_secret: "${JWT_SECRET:dev-secret-key}"
    
  # Monitoring
  monitoring:
    sentry_dsn: "${SENTRY_DSN:}"
    datadog_api_key: "${DATADOG_API_KEY:}"

# Staging Environment
staging:
  # LLM Provider API Keys
  openai:
    api_key: "${STAGING_OPENAI_API_KEY:}"
    organization_id: "${STAGING_OPENAI_ORG_ID:}"
    
  anthropic:
    api_key: "${STAGING_ANTHROPIC_API_KEY:}"
    
  google:
    cloud_project_id: "${STAGING_GOOGLE_CLOUD_PROJECT_ID:}"
    service_account_key: "${STAGING_GOOGLE_SERVICE_ACCOUNT_KEY:}"
    vertex_ai_location: "${STAGING_VERTEX_AI_LOCATION:us-central1}"
    
  azure:
    openai_api_key: "${STAGING_AZURE_OPENAI_API_KEY:}"
    openai_endpoint: "${STAGING_AZURE_OPENAI_ENDPOINT:}"
    openai_api_version: "${STAGING_AZURE_OPENAI_API_VERSION:2023-12-01-preview}"
  
  # Database secrets
  database:
    connection_string: "${STAGING_DATABASE_URL:}"
    encryption_key: "${STAGING_DB_ENCRYPTION_KEY:}"
    
  # Storage secrets
  storage:
    bigquery_key: "${STAGING_BIGQUERY_SERVICE_ACCOUNT_KEY:}"
    s3_access_key: "${STAGING_AWS_ACCESS_KEY_ID:}"
    s3_secret_key: "${STAGING_AWS_SECRET_ACCESS_KEY:}"
    
  # External integrations
  integrations:
    stripe_secret_key: "${STAGING_STRIPE_SECRET_KEY:}"
    webhook_secret: "${STAGING_WEBHOOK_SECRET:}"
    jwt_secret: "${STAGING_JWT_SECRET:}"
    
  # Monitoring
  monitoring:
    sentry_dsn: "${STAGING_SENTRY_DSN:}"
    datadog_api_key: "${STAGING_DATADOG_API_KEY:}"

# Production Environment
production:
  # LLM Provider API Keys
  openai:
    api_key: "${PROD_OPENAI_API_KEY:}"
    organization_id: "${PROD_OPENAI_ORG_ID:}"
    
  anthropic:
    api_key: "${PROD_ANTHROPIC_API_KEY:}"
    
  google:
    cloud_project_id: "${PROD_GOOGLE_CLOUD_PROJECT_ID:}"
    service_account_key: "${PROD_GOOGLE_SERVICE_ACCOUNT_KEY:}"
    vertex_ai_location: "${PROD_VERTEX_AI_LOCATION:us-central1}"
    
  azure:
    openai_api_key: "${PROD_AZURE_OPENAI_API_KEY:}"
    openai_endpoint: "${PROD_AZURE_OPENAI_ENDPOINT:}"
    openai_api_version: "${PROD_AZURE_OPENAI_API_VERSION:2023-12-01-preview}"
  
  # Database secrets
  database:
    connection_string: "${PROD_DATABASE_URL:}"
    encryption_key: "${PROD_DB_ENCRYPTION_KEY:}"
    
  # Storage secrets
  storage:
    bigquery_key: "${PROD_BIGQUERY_SERVICE_ACCOUNT_KEY:}"
    s3_access_key: "${PROD_AWS_ACCESS_KEY_ID:}"
    s3_secret_key: "${PROD_AWS_SECRET_ACCESS_KEY:}"
    
  # External integrations
  integrations:
    stripe_secret_key: "${PROD_STRIPE_SECRET_KEY:}"
    webhook_secret: "${PROD_WEBHOOK_SECRET:}"
    jwt_secret: "${PROD_JWT_SECRET:}"
    
  # Monitoring
  monitoring:
    sentry_dsn: "${PROD_SENTRY_DSN:}"
    datadog_api_key: "${PROD_DATADOG_API_KEY:}"

# Security Configuration
security:
  # Encryption keys
  data_encryption_key: "${DATA_ENCRYPTION_KEY:}"
  password_salt: "${PASSWORD_SALT:}"
  session_secret: "${SESSION_SECRET:}"
  
  # API security
  api_rate_limit_secret: "${RATE_LIMIT_SECRET:}"
  cors_secret: "${CORS_SECRET:}"
  
  # Certificate management
  ssl_certificate: "${SSL_CERT_PATH:}"
  ssl_private_key: "${SSL_KEY_PATH:}"
  ca_certificate: "${CA_CERT_PATH:}"

# Third-party Service Secrets
third_party:
  # Communication platforms
  twilio:
    account_sid: "${TWILIO_ACCOUNT_SID:}"
    auth_token: "${TWILIO_AUTH_TOKEN:}"
    phone_number: "${TWILIO_PHONE_NUMBER:}"
    
  sendgrid:
    api_key: "${SENDGRID_API_KEY:}"
    from_email: "${SENDGRID_FROM_EMAIL:}"
    
  # Analytics and monitoring
  google_analytics:
    tracking_id: "${GA_TRACKING_ID:}"
    measurement_id: "${GA_MEASUREMENT_ID:}"
    
  mixpanel:
    project_token: "${MIXPANEL_TOKEN:}"
    api_secret: "${MIXPANEL_SECRET:}"
    
  # Social media platforms
  facebook:
    app_id: "${FACEBOOK_APP_ID:}"
    app_secret: "${FACEBOOK_APP_SECRET:}"
    page_access_token: "${FACEBOOK_PAGE_TOKEN:}"
    
  instagram:
    app_id: "${INSTAGRAM_APP_ID:}"
    app_secret: "${INSTAGRAM_APP_SECRET:}"
    access_token: "${INSTAGRAM_ACCESS_TOKEN:}"
    
  whatsapp:
    business_account_id: "${WHATSAPP_BUSINESS_ID:}"
    phone_number_id: "${WHATSAPP_PHONE_ID:}"
    access_token: "${WHATSAPP_ACCESS_TOKEN:}"
    webhook_verify_token: "${WHATSAPP_WEBHOOK_VERIFY:}"

# Cloud Provider Secrets
cloud_providers:
  # AWS
  aws:
    access_key_id: "${AWS_ACCESS_KEY_ID:}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY:}"
    region: "${AWS_REGION:us-east-1}"
    s3_bucket: "${AWS_S3_BUCKET:}"
    
  # Google Cloud
  gcp:
    project_id: "${GOOGLE_CLOUD_PROJECT_ID:}"
    service_account_key: "${GOOGLE_SERVICE_ACCOUNT_KEY:}"
    storage_bucket: "${GCP_STORAGE_BUCKET:}"
    
  # Azure
  azure:
    subscription_id: "${AZURE_SUBSCRIPTION_ID:}"
    tenant_id: "${AZURE_TENANT_ID:}"
    client_id: "${AZURE_CLIENT_ID:}"
    client_secret: "${AZURE_CLIENT_SECRET:}"
    storage_account: "${AZURE_STORAGE_ACCOUNT:}"

# Configuration metadata
version: "1.0.0"
last_updated: "2025-07-29"
schema_version: "secrets-v1"