---
# BigQuery Configuration for Agent Wizard Microservice
# This file contains all BigQuery connection and operational settings

bigquery:
  # Google Cloud Project Configuration
  project_id: "${GOOGLE_CLOUD_PROJECT_ID}"
  
  # Dataset Configuration
  dataset_id: "${BIGQUERY_DATASET_ID:agenthub_dev}"
  location: "${BIGQUERY_LOCATION:us-central1}"
  
  # Table Configuration
  tables:
    agents: "${AGENTS_TABLE_ID:agents}"
    conversations: "${CONVERSATIONS_TABLE_ID:conversations}"
  
  # Authentication
  service_account:
    # Path to service account key file
    key_file: "${GOOGLE_APPLICATION_CREDENTIALS}"
    # Or base64 encoded key
    key_json: "${GOOGLE_SERVICE_ACCOUNT_KEY}"
  
  # Query Configuration
  query_settings:
    # Query timeout in seconds
    timeout: "${BIGQUERY_QUERY_TIMEOUT:30}"
    # Maximum number of retries
    max_retries: "${BIGQUERY_MAX_RETRIES:3}"
    # Retry delay in seconds
    retry_delay: "${BIGQUERY_RETRY_DELAY:1}"
    # Enable query logging
    enable_logging: "${BIGQUERY_ENABLE_LOGGING:true}"
  
  # Performance Settings
  performance:
    # Maximum rows per query result
    max_results: "${BIGQUERY_MAX_RESULTS:10000}"
    # Enable query caching
    use_query_cache: "${BIGQUERY_USE_CACHE:true}"
    # Enable legacy SQL (false for standard SQL)
    use_legacy_sql: false
    # Job priority (BATCH or INTERACTIVE)
    job_priority: "${BIGQUERY_JOB_PRIORITY:INTERACTIVE}"
  
  # Security Settings
  security:
    # Enable audit logging
    enable_audit_log: "${BIGQUERY_AUDIT_LOG:true}"
    # Encrypt data at rest
    encryption_enabled: true
    # Require SSL connections
    require_ssl: true
  
  # Development Settings
  development:
    # Enable sample data creation
    create_sample_data: "${BIGQUERY_CREATE_SAMPLES:true}"
    # Enable query debugging
    debug_queries: "${BIGQUERY_DEBUG:false}"
    # Dry run mode (validate queries without execution)
    dry_run: "${BIGQUERY_DRY_RUN:false}"

# Environment-specific configurations
environments:
  development:
    dataset_id: "agenthub_dev"
    create_sample_data: true
    debug_queries: true
    enable_logging: true
    
  staging:
    dataset_id: "agenthub_staging"
    create_sample_data: false
    debug_queries: false
    enable_logging: true
    
  production:
    dataset_id: "agenthub_prod"
    create_sample_data: false
    debug_queries: false
    enable_logging: false
    job_priority: "BATCH"
    max_results: 1000

# Table schemas and configurations
table_configs:
  agents:
    description: "Agent configurations and metadata"
    partition_field: "created_at"
    partition_type: "DAY"
    clustering_fields: ["industry", "status"]
    expiration_days: 365
    
  conversations:
    description: "Agent conversation logs and analytics"
    partition_field: "timestamp"
    partition_type: "DAY" 
    clustering_fields: ["agent_id", "timestamp"]
    expiration_days: 90

# Sample data configuration
sample_data:
  agents:
    count: 5
    industries: ["healthcare", "retail", "finance", "technology"]
    models: ["gpt-4-turbo", "gpt-3.5-turbo", "claude-3-sonnet"]
    
  conversations:
    count: 20
    tokens_range: [100, 1000]
    cost_range: [0.01, 0.50]

# Monitoring and alerts
monitoring:
  # Enable BigQuery job monitoring
  job_monitoring: true
  # Query performance thresholds
  slow_query_threshold: 10 # seconds
  # Cost monitoring thresholds
  daily_cost_limit: 10.00 # USD
  monthly_cost_limit: 300.00 # USD

# Backup and retention
backup:
  # Enable automatic backups
  enabled: true
  # Backup retention in days
  retention_days: 30
  # Backup schedule (cron format)
  schedule: "0 2 * * *" # Daily at 2 AM UTC

# Configuration metadata
version: "1.0.0"
last_updated: "2025-07-28"
format_version: "yaml-1.2"