---
# Environment Secrets Configuration for AgentHub Platform
# This file defines all required API keys and secrets for different environments

# Template for environment variables
# Copy appropriate section to your .env file

# Development Environment Secrets
development:
  # Google Cloud / Vertex AI
  google_cloud:
    project_id: "your-dev-project-id"
    service_account_key: "path/to/dev-service-account.json"
    vertex_ai_location: "us-central1"
  
  # OpenAI
  openai:
    api_key: "sk-your-dev-openai-api-key"
    organization_id: "org-your-dev-organization"
  
  # Anthropic Claude
  anthropic:
    api_key: "sk-ant-your-dev-anthropic-key"
  
  # Azure OpenAI (optional)
  azure_openai:
    api_key: "your-dev-azure-openai-key"
    endpoint: "https://your-dev-resource.openai.azure.com/"
    api_version: "2024-02-01"
    gpt4_deployment_name: "gpt-4-dev"

# Staging Environment Secrets
staging:
  # Google Cloud / Vertex AI
  google_cloud:
    project_id: "your-staging-project-id"
    service_account_key: "path/to/staging-service-account.json"
    vertex_ai_location: "us-central1"
  
  # OpenAI
  openai:
    api_key: "sk-your-staging-openai-api-key"
    organization_id: "org-your-staging-organization"
  
  # Anthropic Claude
  anthropic:
    api_key: "sk-ant-your-staging-anthropic-key"
  
  # Azure OpenAI (optional)
  azure_openai:
    api_key: "your-staging-azure-openai-key"
    endpoint: "https://your-staging-resource.openai.azure.com/"

# Production Environment Secrets
production:
  # Google Cloud / Vertex AI
  google_cloud:
    project_id: "your-prod-project-id"
    service_account_key: "path/to/prod-service-account.json"
    vertex_ai_location: "us-central1"
  
  # OpenAI
  openai:
    api_key: "sk-your-prod-openai-api-key"
    organization_id: "org-your-prod-organization"
  
  # Anthropic Claude
  anthropic:
    api_key: "sk-ant-your-prod-anthropic-key"
  
  # Azure OpenAI (optional)
  azure_openai:
    api_key: "your-prod-azure-openai-key"
    endpoint: "https://your-prod-resource.openai.azure.com/"

# Environment Variable Names Reference
# Use these exact names in your .env files

environment_variables:
  # Google Cloud / Vertex AI
  - GOOGLE_CLOUD_PROJECT_ID
  - GOOGLE_APPLICATION_CREDENTIALS
  - GOOGLE_SERVICE_ACCOUNT_KEY
  - VERTEX_AI_LOCATION
  - VERTEX_AI_TIMEOUT
  - VERTEX_AI_MAX_RETRIES
  - VERTEX_AI_RETRY_DELAY
  
  # OpenAI
  - OPENAI_API_KEY
  - OPENAI_ORGANIZATION_ID
  - OPENAI_TIMEOUT
  - OPENAI_MAX_RETRIES
  - OPENAI_RETRY_DELAY
  
  # Anthropic
  - ANTHROPIC_API_KEY
  - ANTHROPIC_TIMEOUT
  - ANTHROPIC_MAX_RETRIES
  - ANTHROPIC_RETRY_DELAY
  
  # Azure OpenAI
  - AZURE_OPENAI_API_KEY
  - AZURE_OPENAI_ENDPOINT
  - AZURE_OPENAI_API_VERSION
  - AZURE_GPT4_DEPLOYMENT_NAME
  
  # Feature Flags
  - LLM_DEBUG_LOGGING
  - LLM_DETAILED_LOGGING
  - LLM_SANDBOX_MODE
  
  # Rate Limiting
  - LLM_RATE_LIMIT_ENABLED
  - LLM_MAX_REQUESTS_PER_MINUTE
  - LLM_MAX_TOKENS_PER_MINUTE

# Security Best Practices
security_notes:
  - "Never commit API keys to version control"
  - "Use different keys for different environments"
  - "Rotate API keys regularly (90 days recommended)"
  - "Use service account keys with minimal required permissions"
  - "Monitor API usage and set billing alerts"
  - "Enable audit logging for all AI service calls"
  - "Use environment variables or secure secret management"
  - "Implement rate limiting to prevent abuse"

# Setup Instructions
setup_instructions:
  google_cloud:
    - "Create Google Cloud project"
    - "Enable required APIs (Vertex AI, BigQuery, etc.)"
    - "Create service account with appropriate roles"
    - "Download service account key JSON file"
    - "Set GOOGLE_APPLICATION_CREDENTIALS environment variable"
  
  openai:
    - "Create OpenAI account"
    - "Generate API key in OpenAI dashboard"
    - "Set OPENAI_API_KEY environment variable"
    - "Optional: Set organization ID for team accounts"
  
  anthropic:
    - "Create Anthropic account"
    - "Generate API key in Anthropic console"
    - "Set ANTHROPIC_API_KEY environment variable"
  
  azure_openai:
    - "Create Azure account"
    - "Create Azure OpenAI resource"
    - "Deploy models (GPT-4, GPT-3.5, etc.)"
    - "Get API key and endpoint from Azure portal"
    - "Set AZURE_OPENAI_API_KEY and AZURE_OPENAI_ENDPOINT"

# API Key Validation Patterns
validation_patterns:
  openai_api_key: "^sk-[a-zA-Z0-9]{32,}$"
  anthropic_api_key: "^sk-ant-[a-zA-Z0-9-_]{95,}$"
  google_project_id: "^[a-z][a-z0-9-]{4,28}[a-z0-9]$"
  azure_api_key: "^[a-f0-9]{32}$"

# Cost Monitoring Thresholds
cost_monitoring:
  daily_alerts:
    development: 10.00    # USD
    staging: 25.00        # USD
    production: 100.00    # USD
  
  monthly_alerts:
    development: 200.00   # USD
    staging: 500.00       # USD
    production: 2000.00   # USD

version: "1.0.0"
last_updated: "2025-07-29"